### PR TITLE
Blog app - controllers specs

### PR DESCRIPTION
**Pull request by rebaz36**
## Hey Reviewer in this PR I have completed the following

- Created a new branch according to GitHub flow rules.
- Add User and Post controller tests.
- Made sure that renders the correct template.
- Made sure that the response status was correct.
- Made sure that displays the right placeholder.

### Test Results

Screenshot 2023-01-24 at 12 47 16

### CODE REVIEW

**Review by m05e5 — CHANGES_REQUESTED** [review]
Hi @rebaz36 , 

Good job so far. !
There are some issues that you still need to work on to go to the next project but you are almost there!
mario_ladders


## Highlights


## Required Changes ♻️
* You really did a great job but there are some features you need to improve

- [x] Please check the comments below 
- [x] Hi currently you have the `create_users`, `create_posts`, and `create_likes` at the bottom of your migration files which create conflicts when trying to run your migrations 
image

- [x] Please kindly make sure all your test cases are passing correctly. it seems like you have issues in your test configurations 
image

_I'm sure you can do it just keep it up_

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_@m05e5_

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by TedLivist** [comment]
## STATUS: INVALID CODE REVIEW REQUEST 🛑 🛑

Hi @rebaz36,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### You have submitted a project with failing linters

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by rebaz36** [comment]
Rspec Tests Results

Screenshot 2023-01-24 at 12 47 16

**Comment by rebaz36** [comment]
thanks for the comments @TedLivist , and @m05e5

**Review by uwadonat — APPROVED** [review]
## Hi @rebaz36,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### Congratulations! 🎉 
### Highlights
- Professional readme file ✔️
- No linter errors ✔️
- Gitflow was used ✔️
- Well organized project ✔️


thanks-awesome
# Status: Approved ✔️✔️✔️

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100%.
Please, remember to tag me @uwadonat in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by rebaz36** [comment]
thank you @uwadonat

**Pull request merged**
